typography_spectrum: 0.4450153587386012
color:
  brandStrength: 0.6775591252371669
  lightness: 0.3718125051818788
  saturation: 0.9371737835463136
  rhythmicContrast: 0.17473922111093998
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.7106299696024507
author:
  name: Wade Warren
  email: wade@fociss.com
  url: www.fociss.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/280a1735-0342-4c7e-b6cd-018a545fcffb.png
name: FOCISS Travel Systems
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/16cfc5fc-294c-4e03-90f9-4885ce18e769.jpg
title: Travel The Way We Know It Can Now Change
